# Site settings
title: Mahendra Mariadassou
email: mahendra.mariadassou[at]inra.fr
description: > # this means to ignore newlines until "baseurl:"
  Researcher in statistics
baseurl: '' # /mahendra-mariadassou.github.io # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  mahendra-mariadassou

# Build settings
markdown: kramdown # redcarpet
highlighter: rouge # pygments
